# Generated by Django 4.2.7 on 2023-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='photos/2023/11/08/1.jpg', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('name', models.TextField(default='групповой чат')),
                ('user2', models.TextField(default='владелец')),
                ('title2', models.TextField(max_length=20, verbose_name='Название группового чата')),
                ('title_group', models.TextField(verbose_name='Описание группового чата')),
            ],
        ),
    ]
